### ISSUE TITLE
Cannot install fishion with fisher

### ISSUE THREAD

**Issue by sbstn87** [kidonng/fishion#1]
Hi,

when trying to install fishion, I get a list of errors. This the whole output:

<details>
<summary>Output</summary>

command 'apm' not found, did you mean:
  command 'apf' from deb apf-firewall
  command 'gpm' from deb gpm
  command 'apt' from deb apt
  command 'apg' from deb apg
  command 'cpm' from deb cpm
  command 'bpm' from deb bpm-tools
  command 'pm' from deb powerman
  command 'rpm' from deb rpm
  command 'epm' from deb epm
  command 'aim' from deb abinit
  command 'npm' from deb npm
Try: sudo apt install <deb name>
~/.config/fish/completions/apm.fish (line 72): 
if apm -h 2>| string match -q "*Atom Package Manager*"
   ^~^
from sourcing file ~/.config/fish/completions/apm.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'cargo' not found, but can be installed with:
sudo apt install cargo
~/.config/fish/completions/cargo.fish (line 1): 
cargo --list 2>&1 | string replace -rf '^\s+([^\s]+)\s*(.*)' '$1\t$2' | string escape
^~~~^
in command substitution
        called on line 4 of file ~/.config/fish/completions/cargo.fish
from sourcing file ~/.config/fish/completions/cargo.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
~/.config/fish/completions/cargo.fish (line 4): Unknown command
set -l __fish_cargo_subcommands (cargo --list 2>&1 | string replace -rf '^\s+([^\s]+)\s*(.*)' '$1\t$2' | string escape)
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file ~/.config/fish/completions/cargo.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'cpupower' not found, but can be installed with:
sudo apt install linux-cpupower
~/.config/fish/completions/cpupower.fish (line 1): 
LC_ALL=C cpupower idle-info | string replace -f 'Available idle states: ' ''
         ^~~~~~~^
in command substitution
        called on line 48 of file ~/.config/fish/completions/cpupower.fish
from sourcing file ~/.config/fish/completions/cpupower.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
~/.config/fish/completions/cpupower.fish (line 48): Unknown command
set -l idlestates (LC_ALL=C cpupower idle-info | string replace -f 'Available idle states: ' '')
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file ~/.config/fish/completions/cpupower.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'cpupower' not found, but can be installed with:
sudo apt install linux-cpupower
~/.config/fish/completions/cpupower.fish (line 1): 
LC_ALL=C cpupower monitor -l 2>&1 | awk '$1 == "Monitor" {gsub(/"/, "", $2); print $2} $1 == "Available" {print $3}'
         ^~~~~~~^
in command substitution
        called on line 57 of file ~/.config/fish/completions/cpupower.fish
from sourcing file ~/.config/fish/completions/cpupower.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
~/.config/fish/completions/cpupower.fish (line 57): Unknown command
set -l monitors (LC_ALL=C cpupower monitor -l 2>&1 | awk '$1 == "Monitor" {gsub(/"/, "", $2); print $2} $1 == "Available" {print $3}')
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file ~/.config/fish/completions/cpupower.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'deno' not found, did you mean:
  command 'reno' from deb python3-reno
Try: sudo apt install <deb name>
~/.config/fish/completions/deno.fish (line 1): 
deno completions fish | source
^~~^
from sourcing file ~/.config/fish/completions/deno.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'exif' not found, but can be installed with:
sudo apt install exif
~/.config/fish/completions/exif.fish (line 1): 
exif --help
^~~^
in command substitution
        called on line 30 of file ~/.config/fish/completions/exif.fish
from sourcing file ~/.config/fish/completions/exif.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
~/.config/fish/completions/exif.fish (line 30): Unknown command
for line in (exif --help)
            ^~~~~~~~~~~~^
from sourcing file ~/.config/fish/completions/exif.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'gh' not found, but can be installed with:
sudo apt install gh
~/.config/fish/completions/gh.fish (line 1): 
gh completion --shell fish
^^
in command substitution
        called on line 4 of file ~/.config/fish/completions/gh.fish
from sourcing file ~/.config/fish/completions/gh.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
~/.config/fish/completions/gh.fish (line 4): Unknown command
set completion "$(gh completion --shell fish)"
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file ~/.config/fish/completions/gh.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'gpg1' not found, but can be installed with:
sudo apt install gnupg1
/usr/share/fish/functions/__fish_complete_gpg.fish (line 1): 
$__fish_complete_gpg_command --version
^~~~~~~~~~~~~~~~~~~~~~~~~~~^
in command substitution
        called on line 19 of file /usr/share/fish/functions/__fish_complete_gpg.fish
in function '__fish_complete_gpg' with arguments 'gpg1'
        called on line 1 of file ~/.config/fish/completions/gpg1.fish
from sourcing file ~/.config/fish/completions/gpg1.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
/usr/share/fish/functions/__fish_complete_gpg.fish (line 19): Unknown command
    if string match -q 'gpg (GnuPG) 1.*' ($__fish_complete_gpg_command --version)
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
in function '__fish_complete_gpg' with arguments 'gpg1'
        called on line 1 of file ~/.config/fish/completions/gpg1.fish
from sourcing file ~/.config/fish/completions/gpg1.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'helm' not found, did you mean:
  command 'elm' from deb elm-compiler
Try: sudo apt install <deb name>
~/.config/fish/completions/helm.fish (line 1): 
helm completion fish | source
^~~^
from sourcing file ~/.config/fish/completions/helm.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
istioctl: command not found
~/.config/fish/completions/istioctl.fish (line 1): 
istioctl completion fish | source
^~~~~~~^
from sourcing file ~/.config/fish/completions/istioctl.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'kind' not found, did you mean:
  command 'find' from deb findutils
  command 'kfind' from deb kfind
  command 'king' from deb king
Try: sudo apt install <deb name>
~/.config/fish/completions/kind.fish (line 2): 
kind completion fish | source
^~~^
from sourcing file ~/.config/fish/completions/kind.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'kubectl' not found, but can be installed with:
sudo apt install kubernetes-client
~/.config/fish/completions/kubectl.fish (line 1): 
kubectl completion fish 2>/dev/null | source
^~~~~~^
from sourcing file ~/.config/fish/completions/kubectl.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'micro' not found, but can be installed with:
sudo apt install micro
~/.config/fish/completions/micro.fish (line 1): 
micro -options | string replace -f -r '^-(\S+)\s.*' '$1'
^~~~^
in command substitution
        called on line 8 of file ~/.config/fish/completions/micro.fish
from sourcing file ~/.config/fish/completions/micro.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
~/.config/fish/completions/micro.fish (line 8): Unknown command
for option in (micro -options | string replace -f -r '^-(\S+)\s.*' '$1')
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file ~/.config/fish/completions/micro.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
op: command not found
~/.config/fish/completions/op.fish (line 1): 
op completion fish | source
^^
from sourcing file ~/.config/fish/completions/op.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'pandoc' not found, but can be installed with:
sudo apt install pandoc
~/.config/fish/completions/pandoc.fish (line 1): 
pandoc --list-input-formats
^~~~~^
in command substitution
        called on line 5 of file ~/.config/fish/completions/pandoc.fish
from sourcing file ~/.config/fish/completions/pandoc.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
~/.config/fish/completions/pandoc.fish (line 5): Unknown command
set -l informats (pandoc --list-input-formats)
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file ~/.config/fish/completions/pandoc.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'pandoc' not found, but can be installed with:
sudo apt install pandoc
~/.config/fish/completions/pandoc.fish (line 1): 
pandoc --list-output-formats
^~~~~^
in command substitution
        called on line 6 of file ~/.config/fish/completions/pandoc.fish
from sourcing file ~/.config/fish/completions/pandoc.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
~/.config/fish/completions/pandoc.fish (line 6): Unknown command
set -l outformats (pandoc --list-output-formats)
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file ~/.config/fish/completions/pandoc.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'pandoc' not found, but can be installed with:
sudo apt install pandoc
~/.config/fish/completions/pandoc.fish (line 1): 
pandoc --list-highlight-styles
^~~~~^
in command substitution
        called on line 7 of file ~/.config/fish/completions/pandoc.fish
from sourcing file ~/.config/fish/completions/pandoc.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
~/.config/fish/completions/pandoc.fish (line 7): Unknown command
set -l highlight_styles (pandoc --list-highlight-styles)
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file ~/.config/fish/completions/pandoc.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'pip2' not found, did you mean:
  command 'pip' from deb python3-pip
  command 'pip3' from deb python3-pip
  command 'pipx' from deb pipx
  command 'nip2' from deb nip2
Try: sudo apt install <deb name>
~/.config/fish/completions/pip2.fish (line 5): 
pip2 completion --fish 2>/dev/null | string replace -r -- " -c\s+pip\b" " -c pip2" | source
^~~^
from sourcing file ~/.config/fish/completions/pip2.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'pipenv' not found, but can be installed with:
sudo apt install pipenv
~/.config/fish/completions/pipenv.fish (line 1): 
_PIPENV_COMPLETE=fish_source pipenv 2>/dev/null
                             ^~~~~^
in command substitution
        called on line 2 of file ~/.config/fish/completions/pipenv.fish
from sourcing file ~/.config/fish/completions/pipenv.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
~/.config/fish/completions/pipenv.fish (line 2): Unknown command
set -l comps (_PIPENV_COMPLETE=fish_source pipenv 2>/dev/null)
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file ~/.config/fish/completions/pipenv.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'pipenv' not found, but can be installed with:
sudo apt install pipenv
~/.config/fish/completions/pipenv.fish (line 1): 
_PIPENV_COMPLETE=source-fish pipenv --completion 2>/dev/null
                             ^~~~~^
in command substitution
        called on line 5 of file ~/.config/fish/completions/pipenv.fish
from sourcing file ~/.config/fish/completions/pipenv.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
~/.config/fish/completions/pipenv.fish (line 5): Unknown command
    set comps (_PIPENV_COMPLETE=source-fish pipenv --completion 2>/dev/null)
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file ~/.config/fish/completions/pipenv.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'pkginfo' not found, but can be installed with:
sudo apt install python3-pkginfo
~/.config/fish/completions/pkginfo.fish (line 2): 
if pkginfo --help 2>/dev/null | string match -qr Python
   ^~~~~~^
from sourcing file ~/.config/fish/completions/pkginfo.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
Command 'rclone' not found, but can be installed with:
sudo apt install rclone
~/.config/fish/completions/rclone.fish (line 1): 
rclone version | string match -rg 'rclone v(.*)' | string split .
^~~~~^
in command substitution
        called on line 1 of file ~/.config/fish/completions/rclone.fish
from sourcing file ~/.config/fish/completions/rclone.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'
~/.config/fish/completions/rclone.fish (line 1): Unknown command
set -l rclone_version (rclone version | string match -rg 'rclone v(.*)' | string split .)
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file ~/.config/fish/completions/rclone.fish
        called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install kidonng/fishion'

</details>

Command apm is not found, and there is no package called like that in Debian 12 repo.

**Comment by kidonng** [comment]
Ouch. Fisher sources all files upon installing/updating a plugin, but you don't want that for this plugin.

I will mark the plugin as unsupported by Fisher. I kindly invite you to try my plugin manager [plug.fish](https://github.com/kidonng/plug.fish), which supports fishion.

**Comment by kidonng** [comment]
I apologize for pushing my pet plugin manager even though it doesn't work either.

Anyway I took a detour and it should now work no matter how you install it (unless your `$fish_complete_path` is messed up by something else).
