### ISSUE TITLE
who should installl it?

### ISSUE THREAD

**Issue by OmiChrome** [kidonng/fishion#4]
i dont get it.
do non-fish-shell developer  install it?

what type of completion are we getting?
readme is too vague.

**Comment by kidonng** [comment]
There [used to be](https://github.com/kidonng/fishion/commit/a2aa1ff2b7a8dd2bb6830b05de6e91b57a9c590c#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L3-R5) more details in the README but for reasons I don't remember it was removed by past me.

You install this plugin to enjoy the latest completions contributed to the upstream fish shell repository, without having to compile fish from master by yourself.
